[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "${API_URL}/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Credentials = "true"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
